bind 0.0.0.0
protected-mode no
port 6379

appendonly yes
appendfsync everysec

save 900 1
save 300 10
save 60 10000

dir /data

maxmemory 384mb
maxmemory-policy allkeys-lru

tcp-keepalive 60
timeout 0
