[project]
name = "auth-service"
version = "0.0.1"
description = "Internal auth service"
authors = [{ name = "qomaeng", email = "qomaeng@gmail.com" }]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "core>=0.0.1",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "src"

[tool.pyright]
include = ["src", "tests"]
exclude = ["**/.*", "**/__pycache__"]
pythonVersion = "3.13"
venvPath = "../../"
venv = ".venv"
typeCheckingMode = "strict"

[[tool.pyright.executionEnvironments]]
root = "src"
