listen_addresses = '*'
port = 5432

shared_buffers = 512MB
effective_cache_size = 1536MB
maintenance_work_mem = 128MB
work_mem = 8MB

max_connections = 50

wal_compression = on
checkpoint_completion_target = 0.9
random_page_cost = 1.1
effective_io_concurrency = 200

log_min_duration_statement = 1000
